# Generated by Django 3.1.2 on 2021-03-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateField(verbose_name='Entry Date')),
                ('fullName', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('otherContacts', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
            ],
        ),
    ]
