# Generated by Django 3.1.7 on 2021-03-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0009_auto_20210324_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='employee',
            order_with_respect_to='department',
        ),
    ]
