# Generated by Django 3.2 on 2021-04-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0017_auto_20210420_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_new_employee',
            field=models.BooleanField(verbose_name='Новый сотрудник'),
        ),
    ]
