# Generated by Django 3.2 on 2021-06-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0022_auto_20210523_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
    ]
