# Generated by Django 3.2 on 2021-06-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0024_auto_20210618_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['created_at', 'position', 'first_name', 'second_name', 'patronymic'], 'verbose_name': 'кандидата', 'verbose_name_plural': 'Кандидат'},
        ),
        migrations.AlterModelOptions(
            name='candidateprospectiveposition',
            options={'verbose_name': 'должность', 'verbose_name_plural': 'Вакантные должности'},
        ),
    ]
