# Generated by Django 3.2 on 2021-06-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_information_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationScheduleParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxCountDays', models.IntegerField(verbose_name='Максимальное количество дней на отпуск')),
            ],
            options={
                'verbose_name_plural': 'VacationScheduleParameters',
            },
        ),
        migrations.CreateModel(
            name='EmployeeVacationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateVacation', models.DateField(verbose_name='Дата начала отпуска')),
                ('endDateVacation', models.DateField(verbose_name='Дата окончания отпуска')),
                ('vacationDays', models.IntegerField(verbose_name='Продолжительность отпуска')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information_site.employee', verbose_name='Id сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='DaysRemainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.IntegerField(verbose_name='Остаток свободных дней отпуска')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information_site.employee', verbose_name='Сотрудник')),
                ('maxCountDays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation_schedule.vacationscheduleparameters', verbose_name='Максимальное число дней отпуска')),
            ],
        ),
    ]
