# Generated by Django 3.2 on 2021-06-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0001_initial'),
        ('vacation_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacationperiod',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information_site.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeevacationperiod',
            name='vacationDays',
            field=models.IntegerField(verbose_name='Продолжительность отпуска (дней)'),
        ),
    ]
