# Generated by Django 3.2 on 2021-05-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0021_employeeservices'),
        ('vacation_schedule', '0002_alter_vacationscheduleparameters_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysRemainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.IntegerField(verbose_name='Остаток свободных дней отпуска')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information_site.employee', verbose_name='Сотрудник')),
                ('maxCountDays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation_schedule.vacationscheduleparameters', verbose_name='Максимальное число дней отпуска')),
            ],
        ),
    ]
