# Generated by Django 3.1.7 on 2021-04-06 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4f50f40-b71d-46b8-a5d5-11755fd9fb91'), editable=False, primary_key=True, serialize=False),
        ),
    ]
