# Generated by Django 3.1.7 on 2021-04-06 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0002_auto_20210406_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottype',
            name='messenger_type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dbbc33a6-c8e6-44d0-90ee-078de287608d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
