# Generated by Django 3.1.7 on 2021-04-06 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0003_auto_20210406_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4895225e-2a98-4675-b3d7-7b8b70ee6841'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тест'),
        ),
    ]
