# Generated by Django 3.1.7 on 2021-04-06 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0004_auto_20210406_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='botType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bots.bottype', verbose_name='Тип бота'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf36ed79-bc8d-4129-968f-42f03b87bf1b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='token',
            field=models.CharField(max_length=100, verbose_name='Токен'),
        ),
    ]
