# Generated by Django 3.2 on 2021-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0007_auto_20210406_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
