# Generated by Django 3.1.7 on 2021-04-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0007_auto_20210406_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDateTime', models.DateTimeField(verbose_name='Время отправки')),
                ('accessRequestChatBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_access_request_chat_bot', to='chat_bots.chatbot', verbose_name='Бот доступа к сервисам')),
                ('newEmployeeChatBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_new_employee_chat_bot', to='chat_bots.chatbot', verbose_name='Бот нового сотрудника')),
            ],
        ),
    ]
