# Generated by Django 3.1.7 on 2021-04-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0008_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='sendDateTime',
        ),
        migrations.AddField(
            model_name='sender',
            name='sendTime',
            field=models.TimeField(default=None, verbose_name='Время отправки'),
            preserve_default=False,
        ),
    ]
