# Generated by Django 3.2 on 2021-04-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0008_alter_bottype_id'),
        ('chat_bots', '0009_auto_20210413_1823'),
    ]

    operations = [
    ]
