# Generated by Django 3.2 on 2021-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0011_auto_20210413_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='channelId',
            field=models.IntegerField(verbose_name='Id канал'),
        ),
    ]
