# Generated by Django 3.2 on 2021-04-23 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0015_delete_messagetosend'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.datetime(2021, 4, 23, 15, 40))),
                ('botType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bots.bottype')),
            ],
        ),
    ]
