# Generated by Django 3.2 on 2021-04-24 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0016_messagetosend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetosend',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 24, 11, 29)),
        ),
    ]
