# Generated by Django 3.2 on 2021-04-27 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0017_alter_messagetosend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetosend',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 27, 19, 6)),
        ),
    ]
