# Generated by Django 3.2 on 2021-04-29 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0018_alter_messagetosend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetosend',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 29, 9, 19)),
        ),
        migrations.AlterField(
            model_name='sender',
            name='accessRequestChannelId',
            field=models.CharField(max_length=50, verbose_name='Id канала о запросе доступа'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='newEmployeeChannelId',
            field=models.CharField(max_length=50, verbose_name='Id канала о новом сотруднике'),
        ),
    ]
