# Generated by Django 3.2 on 2021-05-11 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0019_auto_20210429_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetosend',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 11, 20, 45)),
        ),
    ]
