# Generated by Django 3.1.7 on 2021-03-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0004_auto_20210317_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department', 'position', 'full_name']},
        ),
    ]
