# Generated by Django 3.1.7 on 2021-03-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0005_auto_20210324_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department']},
        ),
    ]
