# Generated by Django 3.1.7 on 2021-03-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0010_auto_20210325_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydepartment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department', 'position', 'full_name']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='employee',
            order_with_respect_to=None,
        ),
    ]
