# Generated by Django 3.1.7 on 2021-03-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0011_auto_20210325_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'ordering': ['name']},
        ),
    ]
