# Generated by Django 3.2 on 2021-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0014_auto_20210413_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['created_at', 'position', 'first_name', 'second_name', 'patronymic']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department', 'position', 'first_name', 'second_name', 'patronymic']},
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_name',
            field=models.CharField(default='test1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(default='test2', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='second_name',
            field=models.CharField(default='test3', max_length=50),
            preserve_default=False,
        ),
    ]
