# Generated by Django 3.2 on 2021-04-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0015_employeeservices'),
        ('employee_information_site', '0018_alter_employee_is_new_employee'),
    ]

    operations = [
    ]
