# Generated by Django 3.2 on 2021-04-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0019_merge_20210422_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeServices',
        ),
    ]
