# Generated by Django 3.2 on 2021-06-18 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information_site', '0023_auto_20210606_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personal_qualities',
            field=models.TextField(blank=True, verbose_name='Личные качества'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_information_site.candidateprospectiveposition', verbose_name='Предполагаемая должность'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='professional_achievements',
            field=models.TextField(blank=True, verbose_name='Профессиональные достижения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='professional_skill',
            field=models.TextField(blank=True, verbose_name='Профессиональные навыки'),
        ),
    ]
