# Generated by Django 3.2 on 2021-06-18 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя бота')),
                ('token', models.CharField(max_length=100, verbose_name='Токен')),
                ('botType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bots.bottype', verbose_name='Тип бота')),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newEmployeeChannelId', models.CharField(max_length=50, verbose_name='Id канала для уведомлений о новом сотруднике')),
                ('accessRequestChannelId', models.CharField(max_length=50, verbose_name='Id канала для запроса доступа к сервисам')),
                ('sendTime', models.TimeField(default=datetime.datetime(2021, 6, 18, 15, 54), verbose_name='Время отправки')),
                ('accessRequestChatBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_access_request_chat_bot', to='chat_bots.chatbot', verbose_name='Бот для запроса доступа к сервисам')),
                ('newEmployeeChatBot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_new_employee_chat_bot', to='chat_bots.chatbot', verbose_name='Бот для уведомлений о новом сотруднике')),
            ],
        ),
        migrations.CreateModel(
            name='MessageToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50, verbose_name='Id канала')),
                ('message', models.CharField(max_length=50, verbose_name='Текст сообщения')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата отправки')),
                ('time', models.TimeField(default=datetime.datetime(2021, 6, 18, 15, 54), verbose_name='Время отправки')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_bots.chatbot', verbose_name='Бот')),
            ],
        ),
    ]
