# Generated by Django 3.2 on 2021-06-18 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetosend',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 18, 20, 18), verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='sendTime',
            field=models.TimeField(default=datetime.datetime(2021, 6, 18, 20, 18), verbose_name='Время отправки'),
        ),
    ]
