# Generated by Django 3.2 on 2021-04-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationscheduleparameters',
            options={'verbose_name_plural': 'VacationScheduleParameters'},
        ),
    ]
